# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sat Nov  6 16:31:28 2010

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class ConfigFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ConfigFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.srclbl = wx.StaticText(self, -1, "Source Folder")
        self.srcvalue = wx.TextCtrl(self, -1, "/media/EOS_DIGITAL/DCIM/100CANON/")
        self.srcselect = wx.Button(self, -1, ". . .")
        self.destlbl = wx.StaticText(self, -1, "Dest. Folder")
        self.destvalue = wx.TextCtrl(self, -1, "/mnt/data/andi/fotos/sessions")
        self.destselect = wx.Button(self, -1, ". . .")
        self.namelbl = wx.StaticText(self, -1, "Name Pattern")
        self.namevalue = wx.TextCtrl(self, -1, "<date>_<name>")
        self.spacepanel1 = wx.Panel(self, -1)
        self.spacepanel3 = wx.Panel(self, -1)
        self.cancelbtn = wx.Button(self, wx.ID_CANCEL, "")
        self.okbtn = wx.Button(self, wx.ID_OK, "")
        self.spacepanel2 = wx.Panel(self, -1)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.evt_cancelbtn, self.cancelbtn)
        self.Bind(wx.EVT_BUTTON, self.evt_okbtn, self.okbtn)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ConfigFrame.__set_properties
        self.SetTitle("Configuration")
        self.srclbl.SetMinSize((100, 17))
        self.srcvalue.SetMinSize((300, 27))
        self.srcselect.SetMinSize((60, 29))
        self.destlbl.SetMinSize((100, 17))
        self.destvalue.SetMinSize((300, 27))
        self.destselect.SetMinSize((60, 29))
        self.namelbl.SetMinSize((100, 17))
        self.namevalue.SetMinSize((300, 27))
        self.spacepanel1.SetMinSize((60, 29))
        self.cancelbtn.SetMinSize((70, 29))
        self.okbtn.SetMinSize((100, 29))
        self.spacepanel2.SetMinSize((60, 29))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ConfigFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.srclbl, 0, wx.ALL|wx.ALIGN_RIGHT, 8)
        sizer_2.Add(self.srcvalue, 1, wx.ALL, 4)
        sizer_2.Add(self.srcselect, 0, wx.ALL, 4)
        sizer_1.Add(sizer_2, 0, wx.EXPAND, 0)
        sizer_4.Add(self.destlbl, 0, wx.ALL|wx.ALIGN_RIGHT, 8)
        sizer_4.Add(self.destvalue, 1, wx.ALL, 4)
        sizer_4.Add(self.destselect, 0, wx.ALL, 4)
        sizer_1.Add(sizer_4, 0, wx.EXPAND, 0)
        sizer_5.Add(self.namelbl, 0, wx.ALL|wx.ALIGN_RIGHT, 8)
        sizer_5.Add(self.namevalue, 1, wx.ALL, 4)
        sizer_5.Add(self.spacepanel1, 0, wx.ALL|wx.EXPAND, 4)
        sizer_1.Add(sizer_5, 0, wx.EXPAND, 0)
        sizer_3.Add(self.spacepanel3, 1, wx.EXPAND, 0)
        sizer_3.Add(self.cancelbtn, 0, wx.ALL, 4)
        sizer_3.Add(self.okbtn, 0, wx.ALL, 4)
        sizer_3.Add(self.spacepanel2, 0, wx.ALL|wx.EXPAND, 4)
        sizer_1.Add(sizer_3, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade

    def evt_cancelbtn(self, event): # wxGlade: ConfigFrame.<event_handler>
        self.Close()

    def evt_okbtn(self, event): # wxGlade: ConfigFrame.<event_handler>
        import FileList
        self.filelist = FileList.FileList(self)
        self.filelist.Filter()
        self.filelist.ShowDialog()

    def GetSource(self):
        return self.srcvalue.GetValue()

    def GetDest(self):
        return self.destvalue.GetValue()

    def GetName(self):
        return self.namevalue.GetValue()

# end of class ConfigFrame


