# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sat Nov  6 17:17:06 2010

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class CopyDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: CopyDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.headerlbl = wx.TextCtrl(self, -1, "These files will be copied for date <date>:", style=wx.NO_BORDER)
        self.filelst = wx.ListCtrl(self, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.destlbl = wx.StaticText(self, -1, "Dest. Folder")
        self.destvalue = wx.TextCtrl(self, -1, "")
        self.namelbl = wx.StaticText(self, -1, "Name Pattern")
        self.namevalue = wx.TextCtrl(self, -1, "")
        self.spacepanel1 = wx.Panel(self, -1)
        self.cancelbtn = wx.Button(self, wx.ID_CANCEL, "")
        self.okbtn = wx.Button(self, wx.ID_OK, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: CopyDialog.__set_properties
        self.SetTitle("dialog_1")
        self.SetSize((786, 620))
        self.SetForegroundColour(wx.Colour(0, 0, 0))
        self.headerlbl.SetMinSize((300, 27))
        self.filelst.Enable(False)
        self.destlbl.SetMinSize((100, 17))
        self.destvalue.SetMinSize((300, 27))
        self.destvalue.Enable(False)
        self.namelbl.SetMinSize((100, 17))
        self.namevalue.SetMinSize((300, 27))
        self.cancelbtn.SetMinSize((70, 29))
        self.okbtn.SetMinSize((100, 29))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: CopyDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.headerlbl, 1, wx.ALL, 4)
        sizer_1.Add(sizer_2, 0, wx.EXPAND, 0)
        sizer_1.Add(self.filelst, 1, wx.EXPAND, 0)
        sizer_8.Add(self.destlbl, 0, wx.ALL|wx.ALIGN_RIGHT, 8)
        sizer_8.Add(self.destvalue, 1, wx.ALL, 4)
        sizer_1.Add(sizer_8, 0, wx.EXPAND, 0)
        sizer_9.Add(self.namelbl, 0, wx.ALL|wx.ALIGN_RIGHT, 8)
        sizer_9.Add(self.namevalue, 1, wx.ALL, 4)
        sizer_1.Add(sizer_9, 0, wx.EXPAND, 0)
        sizer_3.Add(self.spacepanel1, 1, wx.EXPAND, 0)
        sizer_3.Add(self.cancelbtn, 0, wx.ALL, 4)
        sizer_3.Add(self.okbtn, 0, wx.ALL, 4)
        sizer_1.Add(sizer_3, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def evt_importbtn(self, event): # wxGlade: CopyDialog.<event_handler>
        print "Event handler `evt_importbtn' not implemented!"
        event.Skip()

    def SetDate(self, date):
        text = self.headerlbl.GetValue()
        text = text.replace("<date>" ,date)
        self.headerlbl.SetValue(text)

    def SetDestination(self, dest):
        self.destvalue.SetValue(dest)

    def SetPattern(self, pattern):
        self.namevalue.SetValue(pattern)

    def SetFiles(self, files):
        self.filelst.InsertColumn(0,"Name",width=self.filelst.GetSize().width)

        for i in files:
            self.filelst.InsertStringItem(100,i)

# end of class CopyDialog


