# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sun Nov  7 13:00:52 2010

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class ImagePanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ImagePanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ImagePanel.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ImagePanel.__do_layout
        pass
        # end wxGlade

# end of class ImagePanel


