################################################################################
# Copyright 2010 Andreas Neustifter (andreas.neustifter@gmail.com)
#
# This file is part of PhotoImport.
#
# PhotoImport is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# PhotoImport is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# PhotoImport. If not, see <http://www.gnu.org/licenses/>.
################################################################################
""" An extension to the wx.Panel that easily shows images. """
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sun Nov  7 13:00:52 2010

import wx
import pyexiv2
import io

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class ImagePanel(wx.Panel):
    """ An extension to the wx.Panel that easily shows images. """

    def __init__(self, *args, **kwds):
        # begin wxGlade: ImagePanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade
        self._imagedata = None
        self._drawdata = None
        self._loadedimage = ""
        self.Bind(wx.EVT_PAINT, self.OnPaint, self)

    def __set_properties(self):
        # begin wxGlade: ImagePanel.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ImagePanel.__do_layout
        pass
        # end wxGlade

    def display(self, imagename):
        """ Loads image from preview or file and converts it properly. """
        if self._loadedimage != imagename:
            exif = pyexiv2.ImageMetadata(imagename)
            exif.read()

            imagetype = ""
            if exif.mime_type == 'image/jpeg' or exif.mime_type == 'image/png':
                filereader = open(imagename,"rb")
                data = filereader.read()
                filereader.close()
                imagetype = exif.mime_type
            else:
                data = exif.previews[-1].data
                imagetype = 'image/jpeg'

            if imagetype == 'image/jpeg':
                self._imagedata = wx.ImageFromStream(io.BytesIO(data), wx.BITMAP_TYPE_JPEG)
            elif imagetype == 'image/png':
                self._imagedata = wx.ImageFromStream(io.BytesIO(data), wx.BITMAP_TYPE_PNG)

            self._loadedimage = imagename

        imagewidth = (float)(self._imagedata.GetWidth())
        imageheigth = (float)(self._imagedata.GetHeight())
        panelwidth, panelheight = self.GetSizeTuple()

        scale = imagewidth/(float)(panelwidth)
        if (imageheigth/panelheight) > scale:
            scale = imageheigth/(float)(panelheight)

        self._drawdata = self._imagedata.Copy()
        self._drawdata.Rescale(imagewidth/scale, imageheigth/scale)

        self.Refresh(True)

    def OnPaint(self, event):
        """
        This paints the panel.
        """
        drawingcontext = wx.PaintDC(self)
        if self._imagedata:
            drawingcontext.DrawBitmap(self._drawdata.ConvertToBitmap(), 0, 0)
        event.Skip()

# end of class ImagePanel


