# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Mon Mar 11 20:37:32 2013

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade


class NoImageCopied(wx.Dialog):
    def __init__(self, *args, **kwds):
        if "message" in kwds.keys():
            self.messagetext = kwds.pop("message")
        else:
            self.messagetext = "No images were copied."

        # begin wxGlade: NoImageCopied.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.message = wx.StaticText(self, -1, self.messagetext)
        self.spacepanel1_copy = wx.Panel(self, -1)
        self.okbtn_copy = wx.Button(self, wx.ID_OK, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.evt_okbtn, self.okbtn_copy)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: NoImageCopied.__set_properties
        self.SetTitle("No Image Copied")
        self.okbtn_copy.SetMinSize((100, 29))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: NoImageCopied.__do_layout
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_5_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7.Add(self.message, 1, wx.ALL | wx.EXPAND, 30)
        sizer_5_copy.Add(self.spacepanel1_copy, 1, wx.EXPAND, 0)
        sizer_5_copy.Add(self.okbtn_copy, 0, wx.ALL, 4)
        sizer_7.Add(sizer_5_copy, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_7)
        sizer_7.Fit(self)
        self.Layout()
        # end wxGlade

    def evt_okbtn(self, event):  # wxGlade: NoImageCopied.<event_handler>
        event.Skip()

# end of class NoImageCopied
