# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sun Nov  7 12:53:11 2010

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class wxImagePane(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: wxImagePane.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: wxImagePane.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wxImagePane.__do_layout
        pass
        # end wxGlade

# end of class wxImagePane


