# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sun Nov  7 12:55:22 2010

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class wxImagePanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: wxImagePanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: wxImagePanel.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wxImagePanel.__do_layout
        pass
        # end wxGlade

# end of class wxImagePanel


